version: '3.7'

services:
  shairport:
    build:
      context: .
      dockerfile: Dockerfile
    image: malibukoko/shairport:latest
    container_name: shairport
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/snd
#    environment:
#      - AIRPLAY_NAME_0=Entree
#      - AIRPLAY_PARAMETER_0=-o alsa -- -d plug:gauche1
#      - AIRPLAY_NAME_1=Salon Sejour Cuisine
#      - AIRPLAY_PARAMETER_1=-o alsa -- -d plug:droite1
#      - AIRPLAY_NAME_2=Entree et Salon Sejour Cuisine
#      - AIRPLAY_PARAMETER_2=-o alsa -- -d plug:stereo1
